### ISSUE TITLE
Missing package name in `\ProvidesPackage` definition

### ISSUE THREAD

**Issue by DigNative** [deepakjois/luapackageloader#3]
The current package definition is as following:

    \ProvidesPackage{}[\luapackageloaderpkgdate\space v\luapackageloaderversion\space Lua package searchers for LuaTeX]

This leads to the warning

    LaTeX Warning: You have requested package `luapackageloader',
                   but the package provides `'.

which is caused by the empty argument of `\ProvidesPackage`.

**Comment by krumeich** [comment]
Hey, thanks for patching this. Any chance of pushing the changed version to CTAN? I'd like to get rid of the warning.

Thanks!

**Comment by DigNative** [comment]
@krumeich Maybe you could post a comment in PR #4 to see if there is a possibility of uploading an updated version to CTAN.

**Comment by deepakjois** [comment]
I suppose this is resolved now.

**Comment by krumeich** [comment]
The CTAN team has accepted the upload. Should be visible within 24h.
